This tutorial was contributed by [Ashwani Rathee](https://github.com/ashwani-rathee) and [Abhiroop Singh](https://github.com/abhiroopsk)

In [ ]:
!python --version

Python 3.7.10


## What is NumPy?
NumPy, which stands for Numerical Python, is a python library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. This tutorial explains the basics of NumPy such as its architecture and environment. It also discusses the various array functions, types of indexing, etc.

In 2005,Travis Oliphant created NumPy Package based on previous NumArray.NumPy is often used along with packages like Pandas,SciPy (Scientific Python) and Mat−plotlib (plotting library). 

###Why use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called "ndarray", it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Audience :
- People who wish to learn about machine learning concepts in future.

#### Prerequisites :
- Basic Understanding of computer programming technologies

#### Method to install : 
If you have Python and PIP already installed on a system, then install it using this command:
```
pip install numpy
```

### Import Numpy 

In [ ]:
import numpy as np 
import matplotlib.pylab as plt
from numpy import random
#np is a common alias for numpy
print("Numpy Version: " ,np.__version__)

Numpy Version:  1.19.5


In [ ]:
#np? #Help function

###Example

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
sample_list=[1,2,3,4,5]
arr = np.array(sample_list,dtype=np.int8) #we can specify the datatype,creates array of rank 1
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Array Creation

#### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(42)
print(arr)

42


#### 1-D Arrays
*An* array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array([1,2,3]) 
b = np.array([[1, 2], [3, 4]]) 
c = np.array([1, 2, 3], dtype = complex) 
print("A : \n",a)
print("B : \n",b)
print("C : \n",c)

A : 
 [1 2 3]
B : 
 [[1 2]
 [3 4]]
C : 
 [1.+0.j 2.+0.j 3.+0.j]


#### Generate Random Array:

In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
np.random.randint(10,50,5) #start,stop,no of values

array([44, 29, 46, 16, 42])

In [ ]:
# print(x1);
print("x2: \n", x2);
# Try to print x3 array
# print(...); 

x2: 
 [[0 1 0 1]
 [5 8 7 9]
 [6 7 0 4]]


#### Other methods: Using Arange,Linspace,Zeros,Ones

In [ ]:
np.arange(0,10,2) #start,stop,size of step

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,10,5) #start,stop,number of values in between

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Ndarray Properties

In [ ]:
print("x2 ndim: ", x2.ndim) # ndim-> the number of dimensions
print("x2 shape:", x2.shape) # shape-> the size of each dimension
print("x2 size: ", x2.size) # size-> the total size of the array
print("x2 datatype: ", x2.dtype) # dtype-> the data type of the array
print("x2 itemsize: ", x2.itemsize,"bytes") # itemsize-> lists size of each array element
print("x2 nbytes: ", x2.nbytes,"bytes") # nbytes->  lists the total size (in bytes) of the array

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
x2 datatype:  int64
x2 itemsize:  8 bytes
x2 nbytes:  96 bytes


In [ ]:
List = [0,'lecture',1.0,5.6234]
# List.dtype
data = np.array(List)
data.dtype

dtype('<U21')

### Array indexing


In [ ]:
#Array indexing
# If we want to access element in different dimensions arrays
# In single dimensional x1 array :  
print(x1)
print("Array 1:",x1[1]);
# In 2-dimensional x2 array :
# print(x2[i,j]);
print(x2)
print("Array 2:",x2[1,1])
# In 3-dimensional x3 array :
print("Array 3:",x3[1,1,1]);

[5 0 3 3 7 9]
Array 1: 0
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Array 2: 6
Array 3: 7


### Array Slicing
Slicing in python means taking elements from one given index to another given index.
A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
x1 = np.arange(10)
print("Example 1:",x1[0:10]) # x1[start:end]
print("Example 2:",x1[0:10:2]) # x1[start:end:step]
print("Example 3:",x1[0:]) # all elements from index 0 to the end of the array
print("Example 4:",x1[:5]) # all elements from beginning to index 5
#Negative slicing can also be done
print("Example 5:",x1[::2]) #return every other element from start index 0 to index 10

x2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Example 6:",x2[0:2, 1:4]) #  slice index 1 to index 4 (not included),2-d array returned

Example 1: [0 1 2 3 4 5 6 7 8 9]
Example 2: [0 2 4 6 8]
Example 3: [0 1 2 3 4 5 6 7 8 9]
Example 4: [0 1 2 3 4]
Example 5: [0 2 4 6 8]
Example 6: [[2 3 4]
 [7 8 9]]


### Array Manipulation

In [ ]:
x1 = np.arange(10)
print("x1:",x1)
x1[0] = 5
print("x1:",x1)

x1: [0 1 2 3 4 5 6 7 8 9]
x1: [5 1 2 3 4 5 6 7 8 9]


In [ ]:
print("x2:\n",x2)
print("Logical operation in arrays:",x2[(x2>3) & (x2<7)])
print("Example 2:",x2[x2>5])

x2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Logical operation in arrays: [4 5 6]
Example 2: [ 6  7  8  9 10]


In [ ]:
new_arr= np.array([0,1,2,1,3,4,1])
print("Print Unique Array:",np.unique(new_arr)) # using np.unique method

Print Unique Array: [0 1 2 3 4]


In [ ]:
print("Array x2 :\n",x2)
print("Array x2':\n",np.transpose(x2)) #Transpose of array 

Array x2 :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array x2':
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
print("Array x2 :\n",x2)
print("Array x2':\n",x2.flatten()) # Flatten the array

Array x2 :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array x2':
 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)
print("Sorted Array x2:\n",x2.sort(axis=1)) 
x2.sort(axis=1) #issues coming here

[[4 3 7 5]
 [5 0 1 5]
 [9 3 0 5]]
Sorted Array x2:
 None


### Array Reshaping


In [ ]:
arr = np.arange(10)
print("Initial Array : ",arr)
print("Initial Array Shape: ",arr.shape)
arr = arr.reshape(2,5)
print("Final Array  : \n",arr)
print("Final Array Shape: ",arr.shape)

Initial Array :  [0 1 2 3 4 5 6 7 8 9]
Initial Array Shape:  (10,)
Final Array  : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Final Array Shape:  (2, 5)


### Array Resizing
- Using Shape
- Using Resize

In [ ]:
# Using Shape
arr = np.array([[1,2,3],[4,5,6]]) 
print(arr.shape) #initially it had two rows and three columns
arr.shape = (3,2) 
print(arr) #Now,It has three rows and two columns

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Using Resize
arr = np.array([[1,2,3],[4,5,6]]) 
print(arr.shape) #initially it had two rows and three columns
arr = arr.reshape(3,2) 
print(arr) #Now,It has three rows and two columns

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Do it yourself
brr = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]]) 
print() # find the brr shape first 
brr.shape = # (4,3) ,resize it to  
print(brr) #How many rows and columns does it have now?

SyntaxError: ignored

### Array Stacking & Splitting


In [ ]:
x1 = np.random.randint(10, size=(3, 3))
x2 = np.random.randint(10, size=(3,3))
print("x1: \n",x1)
print("x2: \n",x2)
print("Vertical Stack: \n",np.vstack((x1,x2))) #useful in pandas if you remember csv
print("Horizontal Stack: \n",np.hstack((x1,x2)))

x1: 
 [[0 7 5]
 [9 0 2]
 [7 2 9]]
x2: 
 [[2 3 3]
 [2 3 4]
 [1 2 9]]
Vertical Stack: 
 [[0 7 5]
 [9 0 2]
 [7 2 9]
 [2 3 3]
 [2 3 4]
 [1 2 9]]
Horizontal Stack: 
 [[0 7 5 2 3 3]
 [9 0 2 2 3 4]
 [7 2 9 1 2 9]]


In [ ]:
print("x1: \n",x1)
print("x2: \n",x2)
x3 = np.delete(x1,2,1)
x4 = np.delete(x2,1,0)
print("x3: \n",x3)
print("x4: \n",x4)

x1: 
 [[0 7 5]
 [9 0 2]
 [7 2 9]]
x2: 
 [[2 3 3]
 [2 3 4]
 [1 2 9]]
x3: 
 [[0 7]
 [9 0]
 [7 2]]
x4: 
 [[2 3 3]
 [1 2 9]]


### Array Copying


In [ ]:
x1 = np.random.randint(10, size=(2, 2))
print("Initial x1:",x1)
x2 = x1 # they will point at same array
x2[0,0] = 2
print(x1,"\n",x2)

x2=x1.view() 
x2[1,1] = 2
print(x1,"\n",x2)

x2=x1.copy()
print(x1,"\n",x2)

Initial x1: [[2 3]
 [2 0]]
[[2 3]
 [2 0]] 
 [[2 3]
 [2 0]]
[[2 3]
 [2 2]] 
 [[2 3]
 [2 2]]
[[2 3]
 [2 2]] 
 [[2 3]
 [2 2]]


### Array Math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions.

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x+2)
print(x + y)
print(np.add(x,2))
print(np.add(x, y))

[[3. 4.]
 [5. 6.]]
[[ 6.  8.]
 [10. 12.]]
[[3. 4.]
 [5. 6.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print(np.remainder(x, y))
print(np.log2(x))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1. 2.]
 [3. 4.]]
[[0.        1.       ]
 [1.5849625 2.       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
np.floor([1.2,3.23,123.21])

array([  1.,   3., 123.])

In [ ]:
np.ceil([1.2,3.23,123.21])

array([  2.,   4., 124.])

In [ ]:
x = np.random.randint(100, size=(4))
y = np.random.randint(100, size=(2,3))
print(y)
print("direct sum:",y.sum(axis=0))
print("cumsum : " ,y.cumsum(axis=0))
print("max:",y.max(axis=0))
print("min:",y.min(axis=0))

[[76 35 86]
 [61 69 87]]
direct sum: [137 104 173]
cumsum :  [[ 76  35  86]
 [137 104 173]]
max: [76 69 87]
min: [61 35 86]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Array Flags
Ndarray object has the following attributes. Its current values are returned
 by this function.
- C_CONTIGUOUS (C) -The data is in a single, C-style contiguous segment
- F_CONTIGUOUS (F) - The data is in a single, Fortran-style contiguous segment	
- OWNDATA (O) - The array owns the memory it uses or borrows it from another object	
- WRITEABLE (W) - The data area can be written to. Setting this to False locks the data, making it read-only
- ALIGNED (A) - The data and all elements are aligned appropriately for the hardware
- UPDATEIFCOPY (U) - This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array

In [ ]:
arr = np.array([1,2,3,4,5]) 
print(arr.flags)

## Resources :


- Nicolas P. Rougier's Book "From Python to Numpy" ->
 [Link](https://www.labri.fr/perso/nrougier/from-python-to-numpy/) || [Link-2](https://github.com/rougier/numpy-tutorial)
- NumPy Official Documentation -> [Link](https://numpy.org/devdocs/user/absolute_beginners.html)
- Kaggle Has plethora of notebooks -> [Link](www.kaggle.com)
- Learning the python hardway -> [Link](https://learnpythonthehardway.org/book/)
- Free Code Camp's Videos -> [Link](https://www.youtube.com/watch?v=QUT1VHiLmmI)
- Edureka's video on Numpy -> [Link](https://www.youtube.com/watch?v=8JfDAm9y_7s) || [Link-2](https://www.edureka.co/blog/python-numpy-tutorial/)
- Derek Banas videos rock(the best) -> [Link](https://www.youtube.com/watch?v=8Y0qQEh7dJg)
- Numpy Playlist -> [Link](https://youtu.be/GB9ByFAIAH4?list=RDQMZI0VMokkS5U)
- Scipy Lectures -> [Link](https://scipy-lectures.org/)
- Machine Learning Plus -> [Link](https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/)
- DataQuest.io Tutorial -> [Link](https://www.dataquest.io/blog/numpy-tutorial-python/)
- Stanford's Lecture on Numpy-> [Link](https://cs231n.github.io/python-numpy-tutorial/#numpy)

